In [3]:
# The objective here is to generate sudoku puzzles depending upon the level of difficulty specified.b

In [4]:
import numpy as np
import import_ipynb
from solve_sudoku import get_row_col_sub_square_elem, check_if_state_is_correct, solve_sudoku
import random

importing Jupyter notebook from solve_sudoku.ipynb


In [8]:
# Update the 3 group of sub square elements that are independent of each other in the bigger grid.
def update_sub_square_elems(number_grid):
    
    for index in [0, 3, 6]:
        (number_grid[index,index], number_grid[index,index + 1], number_grid[index, index + 2], 
         number_grid[index + 1,index], number_grid[index + 1,index + 1], number_grid[index + 1,index + 2], 
         number_grid[index + 2,index], number_grid[index + 2,index + 1], number_grid[index + 2,index + 2]) = np.random.permutation(range(1, 10))
        


In [9]:
# Generate a random 9X9 grid, containing number 1-9 in each row, column and sub square.
def generate_number_grid():
    
    number_grid = np.zeros((9,9))
    master_set = set([i for i in range(10)])
    update_sub_square_elems(number_grid)
    (number_grid, num_stack_iterations) = solve_sudoku(number_grid)
    return number_grid

In [10]:
def generate_random_indices(num_indices):
    random_rows = np.random.randint(0, 9, num_indices)
    random_cols = np.random.randint(0, 9, num_indices)    
    
    random_indices = [(random_rows[i], random_cols[i]) for i in range(len(random_rows))]
    return random_indices

In [11]:
# Update every position given in the indices to 0.
def update_zeros(number_grid, indices):
    new_grid = np.copy(number_grid)
    for (row, col) in indices:
        new_grid[row, col] = 0
    return new_grid  

In [22]:
# Generate puzzle and ensure that we get the original number grid when we solve the same!
def generate_puzzle(num_unknowns):
    
    number_grid = generate_number_grid()
    
    while True:
        new_grid = update_zeros(number_grid, generate_random_indices(num_unknowns))

        (solution, num_stack_iterations) = solve_sudoku(new_grid)
        print("Number of stack iterations is", num_stack_iterations)

        print(solution)
        print(number_grid)

        if (solution == number_grid).all():
            break 
    return new_grid

In [65]:
def generate_puzzle_given_difficulty_level(difficulty_level='EASY'):
    
    num_unknowns_list = list()
    if difficulty_level == 'EASY':
        num_unknowns_list = list([41, 42, 43])
    elif difficulty_level == 'MEDIUM':
        num_unknowns_list = list([49, 50, 51])
    elif difficulty_level == 'HARD':
        num_unknowns_list = list([54, 55, 56])        
    elif difficulty_level == 'EXPERT':
        num_unknowns_list = list([59, 60, 61])
    
    num_unknowns = num_unknowns_list[np.random.randint(0, len(num_unknowns_list))]
    puzzle = generate_puzzle(num_unknowns)
    return puzzle

In [73]:
puzzle = generate_puzzle_given_difficulty_level('EXPERT')
puzzle


## Not solved completely with obvious analysis. Digging further ##


############# Solved with non obvious analysis ###################


####### Solved completely with obvious analysis #################

Number of stack iterations is 0
[[1. 2. 4. 3. 5. 8. 9. 6. 7.]
 [9. 5. 6. 4. 1. 7. 2. 3. 8.]
 [8. 7. 3. 2. 6. 9. 5. 4. 1.]
 [2. 1. 8. 7. 9. 6. 3. 5. 4.]
 [4. 3. 9. 8. 2. 5. 7. 1. 6.]
 [7. 6. 5. 1. 3. 4. 8. 9. 2.]
 [5. 9. 7. 6. 8. 1. 4. 2. 3.]
 [3. 8. 1. 5. 4. 2. 6. 7. 9.]
 [6. 4. 2. 9. 7. 3. 1. 8. 5.]]
[[1. 2. 4. 3. 5. 8. 9. 6. 7.]
 [9. 5. 6. 4. 1. 7. 2. 3. 8.]
 [8. 7. 3. 2. 6. 9. 5. 4. 1.]
 [2. 1. 8. 7. 9. 6. 3. 5. 4.]
 [4. 3. 9. 8. 2. 5. 7. 1. 6.]
 [7. 6. 5. 1. 3. 4. 8. 9. 2.]
 [5. 9. 7. 6. 8. 1. 4. 2. 3.]
 [3. 8. 1. 5. 4. 2. 6. 7. 9.]
 [6. 4. 2. 9. 7. 3. 1. 8. 5.]]


array([[1., 0., 0., 3., 0., 8., 9., 6., 0.],
       [0., 5., 0., 4., 1., 7., 2., 0., 0.],
       [8., 7., 0., 0., 0., 9., 5., 0., 0.],
       [0., 0., 0., 0., 9., 6., 0., 0., 0.],
       [4., 3., 9., 0., 2., 5., 7., 1., 0.],
       [0., 6., 0., 1., 0., 4., 8., 9., 2.],
       [5., 0., 0., 6., 8., 0., 4., 2., 0.],
       [0., 8., 0., 5., 0., 0., 0., 0., 0.],
       [0., 4., 2., 9., 0., 3., 0., 8., 5.]])