In [1]:
# This is my stab at solving the sudoku problem completely!!!

In [2]:
# Relevant imports
import numpy as np
from numpy import unravel_index
from queue import LifoQueue

### Getting the input

Let us focus on getting the input to a numpy array


In [3]:
GIVEN_INPUT = np.array([[0, 0, 0, 0, 6, 8, 0, 3, 0],
                        [1, 9, 0, 0, 0, 0, 0, 0, 0],
                        [8, 0, 3, 1, 0, 0, 2, 0, 0],
                        [4, 0, 0, 0, 5, 1, 0, 6, 0],
                        [7, 0, 0, 0, 2, 0, 0, 0, 4],
                        [0, 0, 0, 0, 7, 0, 8, 0, 0],
                        [0, 1, 0, 0, 0, 5, 0, 0, 7],
                        [0, 0, 4, 0, 0, 0, 0, 0, 0],
                        [0, 5, 0, 0, 3, 0, 1, 0, 0]])

### Helper functions

To help us tackle the big problem!


In [4]:
# Flag to run all the tests given in the program.
INCLUDE_DEBUG_TESTS = True
DEBUG_ARRAY = np.resize([0 ,6, 0, 0, 4, 5, 3, 7, 0,
                         0, 0, 5, 6, 7, 3, 4, 2, 0,
                         0, 0, 4, 0, 0, 0, 0, 0, 1,
                         5, 0, 0, 7, 0, 2, 0, 0, 4,
                         6, 0, 9, 0, 0, 0, 2, 5, 0,
                         8, 0, 7, 0, 0, 9, 0, 0, 3,
                         4, 9, 0, 5, 1, 7, 8, 0, 0,
                         2, 1, 0, 0, 3, 6, 0, 0, 0,
                         0, 5, 0, 0, 2, 0, 1, 0, 0], (9,9))

In [5]:
def get_sub_square_row_col(i):
    return 3*((int)(i/3)) + 1

In [6]:
def get_sub_square_elem_indices(i, j, input_arr=GIVEN_INPUT):
    row = get_sub_square_row_col(i)
    col = get_sub_square_row_col(j)
    cur_list = list()
    for i1 in range(row - 1, row + 2):
        for j1 in range(col - 1, col + 2):
            cur_list.append((i1, j1))
    
    return cur_list

In [7]:
def get_sub_square_all_elem(i, j, input_arr=GIVEN_INPUT):
    row = get_sub_square_row_col(i)
    col = get_sub_square_row_col(j)
    cur_list = list()
    indices_list = get_sub_square_elem_indices(i, j, input_arr)
    for index in indices_list:
        i1 = index[0]
        j1 = index[1]
        cur_list.append(input_arr[i1, j1])        

    return cur_list

In [8]:
def get_sub_square_elem(i, j, input_arr=GIVEN_INPUT):
    cur_list = get_sub_square_all_elem(i, j, input_arr)
    return set(cur_list)

In [9]:
def get_row_indices(i, input_arr=GIVEN_INPUT):
    return list([(i, j) for j in range(9)])

In [10]:
def get_row_all_elem(i, input_arr=GIVEN_INPUT):
    indices_list = get_row_indices(i, input_arr)
    cur_list = list()
    for index in indices_list:
        i1 = index[0]
        j1 = index[1]
        cur_list.append(input_arr[i1, j1])        

    return cur_list


In [11]:
def get_row_elem(i, input_arr=GIVEN_INPUT):
    cur_list = get_row_all_elem(i, input_arr)
    return set(cur_list)    


In [12]:
def get_col_indices(j, input_arr=GIVEN_INPUT):
    return list([(i, j) for i in range(9)])

In [13]:
def get_col_all_elem(j, input_arr=GIVEN_INPUT):
    indices_list = get_col_indices(j, input_arr)
    cur_list = list()
    for index in indices_list:
        i1 = index[0]
        j1 = index[1]
        cur_list.append(input_arr[i1, j1])        

    return cur_list


In [14]:
def get_col_elem(j, input_arr=GIVEN_INPUT):
    cur_list = get_col_all_elem(j, input_arr)
    return set(cur_list)    


In [15]:
def get_all_rel_indices_elem(i, j, input_arr=GIVEN_INPUT):
    row_indices = get_row_indices(i, input_arr)
    col_indices = get_col_indices(j, input_arr)
    sub_square_indices = get_sub_square_elem_indices(i, j, input_arr)
    all_rel_indices = set(row_indices + col_indices + sub_square_indices)
    return all_rel_indices


In [16]:
def get_row_col_sub_square_elem(i, j, input_arr=GIVEN_INPUT):
    row_elem = get_row_elem(i, input_arr)
    col_elem = get_col_elem(j, input_arr)
    sub_square_elem = get_sub_square_elem(i, j, input_arr)
    
    union_elem = row_elem | col_elem | sub_square_elem
    
    return union_elem

In [17]:
# for i in range(9):
#     for j in range(9):
#         val = get_row_col_sub_square_elem(i, j, input_arr=DEBUG_ARRAY)
#         print('    assert(get_row_col_sub_square_elem(' + str(i) + ', ' + str(j) + 
#               ', input_arr=DEBUG_ARRAY) == ' + str(val) + ')')

In [18]:
# for i in range(9):
#     for j in range(9):
#         val = get_num_known_elem_vicinity_cur_elem(i, j, input_arr=DEBUG_ARRAY)
#         print('    assert(get_num_known_elem_vicinity_cur_elem(' + str(i) + ', ' + str(j) + 
#               ', input_arr=DEBUG_ARRAY) == ' + str(val) + ')')

In [19]:
# for i in range(9):
#     for j in range(9):
#         val = get_all_rel_indices_elem(i, j, input_arr=DEBUG_ARRAY)
#         print('    assert(get_all_rel_indices_elem(' + str(i) + ', ' + str(j) + 
#               ', input_arr=DEBUG_ARRAY) == ' + str(val) + ')')

In [20]:
# We count the number of non zero elements in the same row, column, or sub square of the current element.
# This  value is used to fine tune our algorithm later.
def get_num_known_elem_vicinity_cur_elem(i, j, input_arr=GIVEN_INPUT):
    rel_indices = get_all_rel_indices_elem(i, j, input_arr)
    count = 0
    for index in rel_indices:
        (i1, j1) = index
        if input_arr[i1, j1] != 0:
            count += 1
    return count


In [21]:
class explorationState():
    """
        The class which stores the current state of the array as well as the element which is to be explored
    """
    
    
    def __init__(self, row_index, col_index, given_elem, elem_impact, cur_array):
        self.__row_index = row_index
        self.__col_index = col_index
        self.__given_elem = given_elem
        self.__elem_impact = elem_impact
        self.__cur_array = cur_array        

    def get_elements(self):
        return (self.__row_index, self.__col_index, self.__given_elem, self.__elem_impact, self.__cur_array)
    
    def display(self):
        print(self.__row_index, self.__col_index, self.__given_elem, self.__elem_impact, self.__cur_array)    

In [22]:
def check_repetitive_non_zero_elem(input_array):
    repetitive_non_zero_elem = False
    non_zero_elem = [x for x in input_array if x != 0]
    if len(non_zero_elem) != len(set(non_zero_elem)):
        repetitive_non_zero_elem = True
     
    return repetitive_non_zero_elem

In [23]:
def check_if_state_is_correct(output_arr):
    state_correct = True
    for i in range(9):
        row = int(i/3)
        col = i%3

        if (check_repetitive_non_zero_elem(get_row_all_elem(i, input_arr=output_arr)) or 
            check_repetitive_non_zero_elem(get_col_all_elem(i, input_arr=output_arr)) or
            check_repetitive_non_zero_elem(get_sub_square_all_elem(3*row, 3*col, input_arr=output_arr))):
            state_correct = False
            break

    return state_correct
        

In [24]:
# The function takes as input the following:
# (a) The array showing the number of known elements in the vicinity for each position --- array_1
# (b) The array showing the set of possible values for each for position --- array_2
# and returns the following:
# (a) The position (that is the row and column) of the maximum element in array_1, whose corresponding entry in 
#     array_2 has a length of 0 or greater than 1 --- output_1
# (b) The corresponding element in array_2 for the position obtained in output_1
# (c) The corresponding element in array_1 for the position obtained in output_1
def get_max_num_known_elem_row_col(num_known_elem_arr, possible_elems):
    sorted_array = -np.sort(-num_known_elem_arr, axis=None)
    output_row = -1
    output_col = -1
    output_set_vals = set()
    required_elem_found = False
    for elem in sorted_array:
        indices = np.where(num_known_elem_arr == elem)
        row_indices = indices[0]
        col_indices = indices[1]
        assert(len(row_indices) == len(col_indices))
        for i in range(len(row_indices)):
            row = row_indices[i]
            col = col_indices[i]
            given_set = possible_elems[row][col]
 
            # IMPORTANT: We have 2 cases to consider here. When length of the set is 0, it means
            # that set cannot take any element, implying that we are in an erroneous state, on which
            # we exit the loop (though we take note of the corresponding state, since the set is empty,
            # it will not be pushed into the stack, implicitly stopping our traversal through that corresponding
            # path) . If the length of the set is 1, it means that we already know the element
            # in this position and it does not make sense to push it to the stack. 
            if ((len(given_set) == 0) or (len(given_set) > 1)):
                output_row = row
                output_col = col
                output_set_vals = possible_elems[row][col]
                required_elem_found = True
                break
        if required_elem_found:
            break
        
    return (output_row, output_col, output_set_vals, elem) 
    


In [25]:
# The function takes as input the following:
# (a) The array showing the number of known elements in the vicinity for each position --- array_1
# (b) The array showing the set of possible values for each for position --- array_2
# and returns the following:
# (a) The position (that is the row and column) of the least element in array_1, whose corresponding entry in 
#     array_2 has a length of 0 or greater than 1 --- output_1
# (b) The corresponding element in array_2 for the position obtained in output_1
# (c) The corresponding element in array_1 for the position obtained in output_1
def get_min_num_known_elem_row_col(num_known_elem_arr, possible_elems):
    sorted_array = np.sort(num_known_elem_arr, axis=None)
    output_row = -1
    output_col = -1
    output_set_vals = set()
    required_elem_found = False
    for elem in sorted_array:
        indices = np.where(num_known_elem_arr == elem)
        row_indices = indices[0]
        col_indices = indices[1]
        assert(len(row_indices) == len(col_indices))
        for i in range(len(row_indices)):
            row = row_indices[i]
            col = col_indices[i]
            given_set = possible_elems[row][col]
 
            # IMPORTANT: We have 2 cases to consider here. When length of the set is 0, it means
            # that set cannot take any element, implying that we are in an erroneous state, on which
            # we exit the loop (though we take note of the corresponding state, since the set is empty,
            # it will not be pushed into the stack, implicitly stopping our traversal through that corresponding
            # path) . If the length of the set is 1, it means that we already know the element
            # in this position and it does not make sense to push it to the stack. 
            if ((len(given_set) == 0) or (len(given_set) > 1)):
                output_row = row
                output_col = col
                output_set_vals = possible_elems[row][col]
                required_elem_found = True
                break
        if required_elem_found:
            break
        
    return (output_row, output_col, output_set_vals, elem) 
    


In [26]:
# The function takes as input the following:
# (a) The array showing the number of known elements in the vicinity for each position --- array_1
# (b) The array showing the set of possible values for each for position --- array_2
# and returns the following:
# (a) The position (that is the row and column) of the first element in array_1, whose corresponding entry in 
#     array_2 has the least length apart from 1 --- output_1
# (b) The corresponding element in array_2 for the position obtained in output_1
# (c) The corresponding element in array_1 for the position obtained in output_1
def get_min_num_possiblities_first_unknown_elem_row_col(num_known_elem_arr, possible_elems):
    output_row = -1
    output_col = -1
    output_set_vals = set()
    required_elem_found = False

    set_lengths_array  = np.zeros((9,9))
    for i in range(9):
        for j in range(9):
            set_lengths_array[i,j] = len(possible_elems[i][j])
    
    max_set_len = int(np.max(set_lengths_array))
    for length in range(max_set_len + 1):

        # IMPORTANT: We omit the entries having length 1, as these correspond to known elements,
        # which we are not interested in.
        if length == 1:
            continue

        indices = np.where(set_lengths_array == length)
        row_indices = indices[0]
        col_indices = indices[1]
        assert(len(row_indices) == len(col_indices))
        if len(row_indices) > 0:
            output_row = row_indices[0]
            output_col = col_indices[0] 
            num_known_elem = num_known_elem_arr[output_row][output_col]
            output_set_vals = possible_elems[output_row][output_col]
            required_elem_found = True
            break
                
    return (output_row, output_col, output_set_vals, num_known_elem) 

In [27]:
# Get the maximum element as well it's position in a given 2D array.
def get_max_elem_given_indices(impact_arr, row_indices, col_indices):
    max_val = -1000
    output_row = -1
    output_col = -1
    for i in range(len(row_indices)):
        row = row_indices[i]
        col = col_indices[i]
        cur_elem = impact_arr[row][col]
        if cur_elem > max_val:
            max_val = cur_elem
            output_row = row
            output_col = col
    
    return (max_val, output_row, output_col)
        

In [28]:
# Get the minimum element as well it's position in a given 2D array.
def get_min_elem_given_indices(impact_arr, row_indices, col_indices):
    min_val = 1000
    output_row = -1
    output_col = -1
    for i in range(len(row_indices)):
        row = row_indices[i]
        col = col_indices[i]
        cur_elem = impact_arr[row][col]
        if cur_elem < min_val:
            min_val = cur_elem 
            output_row = row
            output_col = col
    
    return (min_val, output_row, output_col)
        

In [29]:
# The function takes as input the following:
# (a) The array showing the number of known elements in the vicinity for each position --- array_1
# (b) The array showing the set of possible values for each for position --- array_2
# and returns the following:
# (a) The position (that is the row and column) of the maximum element in array_1, whose corresponding entry in 
#     array_2 has the least length apart from 1 --- output_1
# (b) The corresponding element in array_2 for the position obtained in output_1
# (c) The corresponding element in array_1 for the position obtained in output_1
def get_min_num_possibilities_max_num_known_elem_row_col(num_known_elem_arr, possible_elems):
    
    output_row = -1
    output_col = -1
    output_set_vals = set()
    required_elem_found = False

    set_lengths_array  = np.zeros((9,9))
    for i in range(9):
        for j in range(9):
            set_lengths_array[i,j] = len(possible_elems[i][j])
    
    max_set_len = int(np.max(set_lengths_array))
    for length in range(max_set_len + 1):
        # IMPORTANT: We omit the entries having length 1, as these correspond to known elements,
        # which we are not interested in.
        if length == 1:
            continue
        indices = np.where(set_lengths_array == length)
        row_indices = indices[0]
        col_indices = indices[1]
        assert(len(row_indices) == len(col_indices))
        if len(row_indices) > 0:
            
            (num_known_elem, output_row, output_col) = get_max_elem_given_indices(num_known_elem_arr, row_indices, col_indices)
            output_set_vals = possible_elems[output_row][output_col]
            required_elem_found = True
            break
        
        
    return (output_row, output_col, output_set_vals, num_known_elem) 
    


In [30]:
# The function takes as input the following:
# (a) The array showing the number of known elements in the vicinity for each position --- array_1
# (b) The array showing the set of possible values for each for position --- array_2
# and returns the following:
# (a) The position (that is the row and column) of the least element in array_1, whose corresponding entry in 
#     array_2 has the least length apart from 1 --- output_1
# (b) The corresponding element in array_2 for the position obtained in output_1
# (c) The corresponding element in array_1 for the position obtained in output_1
def get_min_num_possibilities_min_num_known_elem_row_col(impact_arr, possible_elems):
    
    output_row = -1
    output_col = -1
    output_set_vals = set()
    required_elem_found = False

    set_lengths_array  = np.zeros((9,9))
    for i in range(9):
        for j in range(9):
            set_lengths_array[i,j] = len(possible_elems[i][j])
    
    max_set_len = int(np.max(set_lengths_array))
    for length in range(max_set_len + 1):
        # IMPORTANT: We omit the entries having length 1, as these correspond to known elements,
        # which we are not interested in.
        if length == 1:
            continue
        indices = np.where(set_lengths_array == length)
        row_indices = indices[0]
        col_indices = indices[1]
        assert(len(row_indices) == len(col_indices))
        if len(row_indices) > 0:
            
            (impact, output_row, output_col) = get_min_elem_given_indices(impact_arr, row_indices, col_indices)
            output_set_vals = possible_elems[output_row][output_col]
            required_elem_found = True
            break
        
        
    return (output_row, output_col, output_set_vals, impact) 
    


In [31]:
# The function takes as input the following:
# (a) The array showing the current state of the array, whose values are being discovered --- array_1
# (b) The array showing the set of possible values for each for position --- array_2
# and returns the following:
# (a) The position (that is the row and column) of the first element in array_1, 
#     whose corresponding entry is 0 --- output_1
# (b) The corresponding element in array_2 for the position obtained in output_1
# (c) 0
def get_zero_elem_row_col_num_known_elem(given_array, possible_elems):
    rel_list = list()
    
    indices = np.where(given_array == 0)
    row_indices = indices[0]
    col_indices = indices[1]
    assert(len(row_indices) == len(col_indices))
    
    if len(row_indices) >= 1:
        row = row_indices[0]
        col = col_indices[0]
        given_set = possible_elems[row][col]

        output = (row, col, given_set, 0)
    else:
        output = (-1, -1, set(), 0)
        
    return output

In [32]:
# The function takes as input the following:
# (a) The array showing the current state of the array, whose values are being discovered --- array_1
# (b) The array showing the number of known elements in the vicinity for each position --- array_2
# (c) The array showing the set of possible values for each for position --- array_3
# (d) The mode of the program which is to be used.
# and returns a list of which each entry has the following:
# Row, column, corresponding value of the element as well as it's impact depending on the mode used.
def get_unknown_elem_row_col_as_list(output_arr, impact_arr, possible_elems, run_mode='MIN_NUM_POSSIBILITIES_MIN_NUM_KNOWN_ELEM'):
    rel_list = list()
    
    if run_mode == 'FIRST_UNKNOWN':
        (row, col, corr_possible_elems, cur_impact) = get_zero_elem_row_col_num_known_elem(output_arr, possible_elems)
    elif run_mode == 'MIN_NUM_POSSIBILITIES_FIRST_UNKNOWN':
        (row, col, corr_possible_elems, cur_impact) = \
            get_min_num_possiblities_first_unknown_elem_row_col(impact_arr, possible_elems)
    elif run_mode == 'MAX_NUM_KNOWN_ELEM':
        (row, col, corr_possible_elems, cur_impact) = \
            get_max_num_known_elem_row_col(impact_arr, possible_elems)
    elif run_mode == 'MIN_NUM_POSSIBILITIES_MAX_NUM_KNOWN_ELEM':
        (row, col, corr_possible_elems, cur_impact) = \
            get_min_num_possibilities_max_num_known_elem_row_col(impact_arr, possible_elems)
    elif run_mode == 'MIN_NUM_POSSIBILITIES_MIN_NUM_KNOWN_ELEM':
        (row, col, corr_possible_elems, cur_impact) = \
            get_min_num_possibilities_min_num_known_elem_row_col(impact_arr, possible_elems)
    elif run_mode == 'MIN_NUM_KNOWN_ELEM':
        (row, col, corr_possible_elems, cur_impact) = \
            get_min_num_known_elem_row_col(impact_arr, possible_elems)
    else:
        print('Incorrect mode specified. Using mode MIN_NUM_POSSIBILITIES_MIN_NUM_KNOWN_ELEM by default')
        (row, col, corr_possible_elems, cur_impact) = \
            get_min_num_possibilities_min_num_known_elem_row_col(impact_arr, possible_elems)
        
    for elem in corr_possible_elems:
        rel_list.append((row, col, elem, cur_impact))
        
    return rel_list
    


In [33]:
def sort_items_by_impact_and_push_to_stack(
    output_arr, impact_arr, possible_elems, stack, run_mode='MIN_NUM_POSSIBILITIES_MIN_NUM_KNOWN_ELEM'):

    rel_items = get_unknown_elem_row_col_as_list(output_arr, impact_arr, possible_elems, run_mode)
        
    for item in rel_items:
        (row, col, elem, impact) = item
        stack.put(explorationState(row, col, elem, impact, output_arr))



### Come to the core algorithm

Let us come to the part where the real meat is!


In [34]:
# As the name suggests, we do the obvious analysis for each position of the array, 
# by evaluating all the possiblities of the corresponding row, column and sub square and 
# updating the corresponding position, if only one value was found, which satisifed the constraints
# of Sudoku.
def do_obvious_analysis(input_arr=GIVEN_INPUT): 
    master_set = set(range(1, 10))
    output_arr = np.copy(input_arr)    
    num_zero_elem = np.count_nonzero(output_arr==0)
    num_iterations = 0
    need_to_drill_down = False
    possible_elems = [[set() for i in range(9)] for j in range(9)]
    impact_elems = np.zeros((9,9))
    num_total_updations = 0
    while num_zero_elem > 0:  
        num_updations = 0
        num_iterations += 1
        for i in range(9):
            for j in range(9):
                if output_arr[i, j] == 0:
                    rel_elem = get_row_col_sub_square_elem(i, j, output_arr) 
                    possible_elem = master_set - rel_elem
                    possible_elems[i][j] = possible_elem
                    if len(possible_elem) == 1:
                        output_arr[i, j] = possible_elem.pop()
                        num_updations += 1 
                else:
                    possible_elems[i][j] = set([output_arr[i, j]])
                
                impact_elems[i, j] = get_num_known_elem_vicinity_cur_elem(i, j, input_arr=output_arr)
                        
        num_zero_elem = np.count_nonzero(output_arr==0)

        num_total_updations += num_updations
        if ((num_zero_elem > 0) and (num_updations == 0)):
            break

    return (output_arr, num_zero_elem, num_total_updations, num_iterations, possible_elems, impact_elems)
 

In [35]:
# In this scenario, we push several possible possibilities of the input array to a stack and these 
# are analysed separately, until we find one that satisfies the constraints of Sudoku.
def do_non_obvious_analysis(
    output_arr, impact_arr, possible_elems, run_mode='MIN_NUM_POSSIBILITIES_MIN_NUM_KNOWN_ELEM'):
    
    # DRILL DOWN
    print('\n## Not solved completely with obvious analysis. Digging further ##\n')
    num_stack_iterations = 0
    no_solution_found = True
      
    # Implementation of stack using lifoqueue
    stack = LifoQueue(maxsize=2000)

    sort_items_by_impact_and_push_to_stack(output_arr, impact_arr, possible_elems, stack, run_mode)
    while (not stack.empty()):

        num_stack_iterations += 1
        (row, col, elem, impact, output_arr) = stack.get().get_elements()
        copied_array = np.copy(output_arr)
        copied_array[row][col] = elem

        (output_arr, num_zero_elem, num_updations, num_iterations, possible_elems, impact_arr) = \
            do_obvious_analysis(copied_array)

        if num_zero_elem == 0:
            print('\n############# Solved with non obvious analysis ###################\n')
            no_solution_found = False
            break
        else:
            sort_items_by_impact_and_push_to_stack(output_arr, impact_arr, possible_elems, stack, run_mode)

    return (output_arr, num_stack_iterations, no_solution_found)

In [36]:
def solve_sudoku(input_arr=GIVEN_INPUT, run_mode='MIN_NUM_POSSIBILITIES_MIN_NUM_KNOWN_ELEM', debug_output=False): 

    num_initial_unknowns = np.sum(input_arr == 0)
    no_solution_found = False
    num_stack_iterations = 0
    (output_arr, num_zero_elem, num_updations, num_iterations, possible_elems, impact_array) = \
        do_obvious_analysis(input_arr)
    
    if debug_output:
        print('\n################ Information regarding given input ##############\n') 
        print('Number of unknowns   : ', num_initial_unknowns)    

        print('\n####### Information regarding the initial obvious analysis ######\n')    
        print('Number of iterations : ', num_iterations)
        print('Number of updations  : ', num_updations)
        assert(num_initial_unknowns == (num_zero_elem + num_updations))
    if num_zero_elem ==0: 
        print('\n####### Solved completely with obvious analysis #################\n')
    elif not check_if_state_is_correct(output_arr):
        print('\n####### Wrong input,as no solution found #######\n')        
        no_solution_found = True
    else:
        
        (output_arr, num_stack_iterations, no_solution_found) = do_non_obvious_analysis(output_arr, 
                                                                                        impact_array, 
                                                                                        possible_elems,
                                                                                        run_mode)
            
    if debug_output:
        print("Number of stack iterations : ", num_stack_iterations)
        if not no_solution_found:
            print('\n####### Output ######\n')
            print('\n'.join([''.join(['{:4}'.format(item) for item in row]) 
      for row in output_arr]))
    return (output_arr, num_stack_iterations)

In [37]:
def display_2d_array(input_arr=GIVEN_INPUT):
    (num_rows, num_cols) = np.shape(input_arr)
    for i in range(num_rows):
        for j in range(num_cols):
            print(str(input_arr[i, j]) + '    ')

In [38]:
def main():
    (output_sudoku, num_stack_iterations) = solve_sudoku(input_arr=GIVEN_INPUT,debug_output=True)
    print(output_sudoku)
    (output_sudoku, num_stack_iterations) = solve_sudoku(
        input_arr=GIVEN_INPUT,run_mode='FIRST_UNKNOWN', debug_output=False)
    print(num_stack_iterations)    
    (output_sudoku, num_stack_iterations) = solve_sudoku(
        input_arr=GIVEN_INPUT,run_mode='MIN_NUM_POSSIBILITIES_FIRST_UNKNOWN', debug_output=False)
    print(num_stack_iterations)    
    (output_sudoku, num_stack_iterations) = solve_sudoku(
        input_arr=GIVEN_INPUT,run_mode='MAX_NUM_KNOWN_ELEM', debug_output=False)
    print(num_stack_iterations)    
    (output_sudoku, num_stack_iterations) = solve_sudoku(
        input_arr=GIVEN_INPUT,run_mode='MIN_NUM_POSSIBILITIES_MAX_NUM_KNOWN_ELEM', debug_output=False)
    print(num_stack_iterations)    
    (output_sudoku, num_stack_iterations) = solve_sudoku(
        input_arr=GIVEN_INPUT,run_mode='MIN_NUM_POSSIBILITIES_MIN_NUM_KNOWN_ELEM', debug_output=False)
    print(num_stack_iterations)    

In [39]:
if __name__ == "__main__":
    main()


################ Information regarding given input ##############

Number of unknowns   :  56

####### Information regarding the initial obvious analysis ######

Number of iterations :  2
Number of updations  :  5

## Not solved completely with obvious analysis. Digging further ##


############# Solved with non obvious analysis ###################

Number of stack iterations :  22

####### Output ######

   2   4   7   5   6   8   9   3   1
   1   9   5   3   4   2   6   7   8
   8   6   3   1   9   7   2   4   5
   4   3   9   8   5   1   7   6   2
   7   8   1   9   2   6   3   5   4
   5   2   6   4   7   3   8   1   9
   3   1   2   6   8   5   4   9   7
   6   7   4   2   1   9   5   8   3
   9   5   8   7   3   4   1   2   6
[[2 4 7 5 6 8 9 3 1]
 [1 9 5 3 4 2 6 7 8]
 [8 6 3 1 9 7 2 4 5]
 [4 3 9 8 5 1 7 6 2]
 [7 8 1 9 2 6 3 5 4]
 [5 2 6 4 7 3 8 1 9]
 [3 1 2 6 8 5 4 9 7]
 [6 7 4 2 1 9 5 8 3]
 [9 5 8 7 3 4 1 2 6]]

## Not solved completely with obvious analysis. Digging further ##